#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"

# Random Syslog-formatted logs
# [sources.dummy_logs]
# type = "generator"
# format = "syslog"
# interval = 1

[sources.nginx_access_logs]
type = "file"
include = ["/var/log/nginx/*.log"]
read_from = "beginning"
ignore_checkpoints = true

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
# [transforms.parse_logs]
# type = "remap"
# inputs = ["dummy_logs"]
# source = '''
# . = parse_syslog!(string!(.message))
# '''

[transforms.add_transform]
type = "remap"
inputs = ["nginx_access_logs"]
source = '''
.type = "nginx-access"
'''

# Print parsed logs to stdout
[sinks.print]
type = "console"
inputs = ["add_transform"]
encoding.codec = "json"

# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
#[api]
#enabled = true
#address = "127.0.0.1:8686"
