
################ Apache Logs #############################

[sources.apache_logs]
  type = "file"
  include = [
    null
    "/var/log/apache2/error.log"
  ]
  read_from = "beginning"

[transforms.apache_logs_transform]
  type = "remap"
  inputs = ["apache_logs"]
  source = '''
  .type = "apache-logs"
  '''

[sinks.apache_logs_firehose_stream_sink]
  # General
  type = "aws_kinesis_firehose"
  inputs = ["apache_logs_transform"]

  # AWS
  region = "us-east-2"
  stream_name = "DendroFirehoseStream"

  ## Auth
  auth.access_key_id = "jijijijijijijijijij"
  auth.secret_access_key = "jijijijijijijijijijijijijijijijijijijijijijijij"

  # Encoding
  encoding.codec = "json"

#############################################

################ wewef - Custom Application #############################

[sources.custom_application_wewef_logs]
  type = "file"
  include = ["ex. /var/log/railsApp/railsApp.log"]
  read_from = "beginning"

[transforms.custom_application_wewef_transform]
  type = "remap"
  inputs = ["custom_application_wewef_logs"]
  source = '''
  .type = "custom-application"
  '''

[sinks.custom_application_wewef_logs_firehose_stream_sink]
  # General
  type = "aws_kinesis_firehose"
  inputs = ["custom_application_wewef_logs_transform"]

  # AWS
  region = "us-east-2"
  stream_name = "DendroFirehoseStream"

  ## Auth
  auth.access_key_id = "jijijijijijijijijij"
  auth.secret_access_key = "jijijijijijijijijijijijijijijijijijijijijijijij"

  # Encoding
  encoding.codec = "json"

  # Healthcheck
  healthcheck.enabled = true # optional, default

#############################################

################ Host Logs #############################

[sources.host_metrics]
type = "host_metrics"
collectors = [
  cpu,
  disk,
  filesystem,
  load,
  host,
  memory,
  network,
]
scrape_interval_secs = 15

[transforms.host_metrics_to_logs]
  type = "metric_to_log"
  inputs = ["host_metrics"]

[transforms.host_metrics_transform]
  type = "remap"
  inputs = ["host_metrics_to_logs"]
  source = '''
  .type = "host-metrics"
  '''

[sinks.host_metrics_firehose_stream_sink]
  # General
  type = "aws_kinesis_firehose"
  inputs = ["host_metrics_transform"]

  # AWS
  region = "us-east-2"
  stream_name = "DendroFirehoseStream"

  ## Auth
  auth.access_key_id = "jijijijijijijijijij"
  auth.secret_access_key = "jijijijijijijijijijijijijijijijijijijijijijijij"

  # Encoding
  encoding.codec = "json"

#############################################

################ Mongo Logs #############################

[sources.mongo_logs]
  type = "file"
  include = [
    "/var/log/mongodb/*.log",
  ]
  read_from = "beginning"

[transforms.mongo_logs_transform]
  type = "remap"
  inputs = ["mongo_logs"]
  source = '''
  .type = "mongo-logs"
  '''

[sinks.mongo_logs_firehose_stream_sink]
  # General
  type = "aws_kinesis_firehose"
  inputs = ["mongo_logs_transform"]

  # AWS
  region = "us-east-2"
  stream_name = "DendroFirehoseStream"

  ## Auth
  auth.access_key_id = "jijijijijijijijijij"
  auth.secret_access_key = "jijijijijijijijijijijijijijijijijijijijijijijij"

  # Encoding
  encoding.codec = "json"

#############################################

################ Nginx Logs #############################

[sources.nginx_logs]
  type = "file"
  include = [
    null
    "/var/log/nginx/error_log.log"
  ]
  read_from = "beginning"

[transforms.nginx_logs_transform]
  type = "remap"
  inputs = ["nginx_logs"]
  source = '''
  .type = "nginx-logs"
  '''

[sinks.nginx_logs_firehose_stream_sink]
  # General
  type = "aws_kinesis_firehose"
  inputs = ["nginx_logs_transform"]

  # AWS
  region = "us-east-2"
  stream_name = "DendroFirehoseStream"

  ## Auth
  auth.access_key_id = "jijijijijijijijijij"
  auth.secret_access_key = "jijijijijijijijijijijijijijijijijijijijijijijij"

  # Encoding
  encoding.codec = "json"

#############################################

################ Postgres Logs #############################

[sources.postgres_logs]
  type = "file"
  include = ["/var/log/postgresql/*.log"]
  read_from = "beginning"

[transforms.postgres_logs_transform]
  type = "remap"
  inputs = ["postgres_logs"]
  source = '''
  .type = "postgres-logs"
  '''

[sinks.postgres_logs_firehose_stream_sink]
  # General
  type = "aws_kinesis_firehose"
  inputs = ["postgres_logs_transform"]

  # AWS
  region = "us-east-2"
  stream_name = "DendroFirehoseStream"

  ## Auth
  auth.access_key_id = "jijijijijijijijijij"
  auth.secret_access_key = "jijijijijijijijijijijijijijijijijijijijijijijij"

  # Encoding
  encoding.codec = "json"

#############################################
